version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DB_HOST=db
  optimizer:
    build: ./Optimizer
    ports:
      - "5005:5000"
    links:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=hacktm
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:
