version: "3.9"
services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
    links:
      - db
  optimizer:
    build: ./Optimizer
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
